name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    name: Linux (${{ matrix.cc }})
    runs-on: [self-hosted, linux]
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        cc: [gcc, clang]
    steps:
      - uses: actions/checkout@v4
      - name: Build and test
        run: |
          export CC=${{ matrix.cc }}
          make
          make test
